#' account_stats
#'
#' @description
#' Calculate account statistics: total posts shared, average time delta, average edge symmetry score.
#'
#' @details
#' With this helper function, you can obtain summary statistics for the accounts in
#' the network. When applied to a network for which a narrower `time_window` has
#' been calculated using the \link{flag_speed_share} function, the summary statistics
#' are computed separately for both the full and faster networks. It is possible
#' to further refine the analysis by considering only the nodes that exceed the
#' edge weight threshold (recommended). This filter can be applied to the full
#' network when no faster network is identified by the \link{flag_speed_share} function,
#' or when the network to be filtered is the full network. Alternatively, it can
#' be applied to the fast network when this is preliminary identified via the
#' \link{flag_speed_share} function.
#'
#' @param coord_graph an `igraph` object generated by \link{generate_coordinated_network}
#' @param weight_threshold The threshold to be used for filtering the graph (options: "full", "fast", or "none").

#' @return a data.table with summary statistics for each account
#'
#' @import data.table
#' @import igraph
#' @export
#'
#'

account_stats <- function(coord_graph, weight_threshold = c("full", "fast", "none")) {
    weight_threshold_full <- weight_threshold_fast <- from <- n_content_id_full <-
        n_content_id_fast <- avg_time_delta_full <- avg_time_delta_fast <- edge_symmetry_score_full <-
        edge_symmetry_score_fast <- to <- n_content_id_y_full <- n_content_id_y_fast <- n_content_full <-
        n_content_fast <- account_id <- n_content_id <- avg_time_delta <- edge_symmetry_score <- n_content_id_y <-
        n_content <- NULL



    # Check if "_fast" and "_full" are in column names
    if (any(grepl("_fast", edge_attr_names(coord_graph))) &&
        any(grepl("_full", edge_attr_names(coord_graph)))) {

        # Check if "object_ids" are included and remove the relative attributes
        if (any(grepl("object_ids", edge_attr_names(coord_graph)))) {
            # List of edge attributes to be removed
            edge_attrs_to_remove <-
                c("object_ids_full", "object_ids_fast")

            # Removing edge attributes using a loop
            for (attr in edge_attrs_to_remove) {
                coord_graph <- delete_edge_attr(coord_graph, attr)
            }
        }

        x <-
            data.table::as.data.table(igraph::as_data_frame(coord_graph))

        # Filter by edge weight threshold
        if (weight_threshold == "full") {
            x <- x[weight_threshold_full == 1]
        }

        if (weight_threshold == "fast") {
            x <- x[weight_threshold_fast == 1]
        }

        # Reshape and summarize
        reshaped <- rbind(x[, .(
            account_id = from,
            n_content_full = n_content_id_full,
            n_content_fast = n_content_id_fast,
            avg_time_delta_full,
            avg_time_delta_fast,
            edge_symmetry_score_full,
            edge_symmetry_score_fast
        )],
        x[, .(
            account_id = to,
            n_content_full = n_content_id_y_full,
            n_content_fast = n_content_id_y_fast,
            avg_time_delta_full,
            avg_time_delta_fast,
            edge_symmetry_score_full,
            edge_symmetry_score_fast
        )])

        reshaped <- unique(reshaped)

        account_summary <- reshaped[, .(
            sum_content_full = sum(n_content_full),
            sum_content_fast = sum(n_content_fast),
            avg_time_delta_full = mean(avg_time_delta_full, na.rm = TRUE),
            avg_time_delta_fast = mean(avg_time_delta_fast, na.rm = TRUE),
            avg_edge_symmetry_score_full = mean(edge_symmetry_score_full, na.rm = TRUE),
            avg_edge_symmetry_score_fast = mean(edge_symmetry_score_fast, na.rm = TRUE)
        ), by = .(account_id)]

        account_summary <-
            account_summary[, lapply(.SD, function(x) {
                x[is.nan(x)] <- NA
                return(x)
            })]

        data.table::setorder(account_summary, "account_id")

        return(account_summary)

    }

    if (!any(grepl("_fast", edge_attr_names(coord_graph))) &&
        !any(grepl("_full", edge_attr_names(coord_graph)))) {
        {
            # if the data has not been updated with the `flag_speed_share` function

            # If data includes object_ids, remove unused edge attributes
            if (any(grepl("object_ids", edge_attr_names(coord_graph)))) {
                coord_graph <- delete_edge_attr(coord_graph, "object_ids")
            }

            x <-
                data.table::as.data.table(igraph::as_data_frame(coord_graph))

            # Filter by edge weight threshold
            if (weight_threshold == "full") {
                x <- x[weight_threshold == 1]
            }

            reshaped <- rbind(x[, .(
                account_id = from,
                n_content = n_content_id,
                avg_time_delta,
                edge_symmetry_score
            )],
            x[, .(
                account_id = to,
                n_content = n_content_id_y,
                avg_time_delta,
                edge_symmetry_score
            )])

            # Remove duplicates
            reshaped <- unique(reshaped)

            # Aggregate to find the average values for each account and content pair
            account_summary <- reshaped[, .(
                sum_content = sum(n_content),
                avg_time_delta = mean(avg_time_delta, na.rm = TRUE),
                avg_edge_symmetry_score = mean(edge_symmetry_score, na.rm = TRUE)
            ), by = .(account_id)]

            account_summary <-
                account_summary[, lapply(.SD, function(x) {
                    # Replace NaN with NA
                    x[is.nan(x)] <- NA
                    return(x)
                })]

            data.table::setorder(account_summary, "account_id")
            return(account_summary)
        }
    }
}
